- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "/tmp/vector-{{ vector_version }}.rpm"
    mode: '0644'
  tags:
    - vector
    - install

- name: Update dnf cache
  ansible.builtin.dnf:
    update_cache: true

- name: Install vector
  ansible.builtin.dnf:
    name: "/tmp/vector-{{ vector_version }}.rpm"
    state: present
    disable_gpg_check: true
  changed_when: false
  tags:
    - vector
    - install
  become: true