#SPDX-License-Identifier: MIT-0
---
# - name: Install by YUM repo
#   command:
#     argv: 
#       - /bin/bash 
#       - -c 
#       - $(curl -fsSL {{ vector_repo_url }})
#   register: output
#   tags: [repo]
#   become: true

- name: VECTOR | Check vector version
  command: "{{ vector_exec_name }} --version"
  register: vector_check
  changed_when: false
  ignore_errors: true

- name: Print vector check
  ansible.builtin.debug:
    msg: "VECTOR: {{ vector_check.failed }}"


# - name: VECTOR | Download package
#   apt:
#     deb: "{{ vector_deb_package }}"
#   when: vector_force_reinstall or vector_check is failed or vector_version not in vector_check.stdout

#https://dev.to/ymotongpoo/run-remote-install-scripts-without-using-curl-command-in-ansible-5b6b
- name: Fetch vector repo install script
  ansible.builtin.uri:
    url: "{{ vector_repo_url }}"
    return_content: yes
  register: vector_installer
  tags:
    - vector
    - install
  when: not vector_remove|bool and vector_check.failed|bool

- name: Run vector repo installer
  ansible.builtin.shell:
    cmd: bash -s -- -y
    stdin: "{{ vector_installer.content }}"
  become: true
  tags:
    - vector
    - install
  when: not vector_remove|bool and vector_check.failed|bool

- name: Print pkg manager
  ansible.builtin.debug:
    msg: "PKG: {{ ansible_pkg_mgr }}. MGR: {{ ansible_service_mgr }}"

# - include_tasks:
#     file: "prepare.yml"
#     apply:
#       tags: [install]
#   vars:
#     pkgs:
#       - systemctl
        
- include_tasks:
    file: "{{ lookup('first_found', params) }}"
    apply:
      tags: [install]
  vars:
    params:
      files:
        - "install/{{ ansible_pkg_mgr if ansible_pkg_mgr != 'dnf' else 'rpm' }}.yml"
        - 'install/rpm.yml'
  tags: [install]
  when: not vector_remove|bool

# - name: Deploy vector configuration
#   ansible.builtin.template:
#     src: templates/config/vector.toml.j2
#     dest: "{{ vector_config_path }}"
#     mode: '0644'
#   notify: Start vector service
#   tags:
#     - vector
#     - config
#   become: true
#   when: not vector_remove|bool

- name: VECTOR | User
  include_tasks: user.yml
  tags:
    - vector
    - user
  when: not vector_remove|bool

- name: VECTOR | Configure
  include_tasks: config.yml
  tags:
    - vector
    - configure
  when: not vector_remove|bool

# - name: VECTOR | Service
#   include_tasks: service.yml
#   tags:
#     - vector
#     - service
#   when: not vector_remove|bool

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - vector
    - restart
