#SPDX-License-Identifier: MIT-0
---
# - name: Install by YUM repo
#   command:
#     argv: 
#       - /bin/bash 
#       - -c 
#       - $(curl -fsSL {{ vector_repo_url }})
#   register: output
#   tags: [repo]
#   become: true

#https://dev.to/ymotongpoo/run-remote-install-scripts-without-using-curl-command-in-ansible-5b6b
- name: Fetch vector repo install script
  ansible.builtin.uri:
    url: "{{ vector_repo_url }}"
    return_content: yes
  register: vector_installer
  tags:
    - vector
    - install

- name: Run vector repo installer
  ansible.builtin.shell:
    cmd: sh -s -- -y
    stdin: "{{ vector_installer.content }}"
  become: true
  tags:
    - vector
    - install
   
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "/tmp/vector-{{ vector_version }}.rpm"
    mode: '0644'
  tags:
    - vector
    - install

- name: Update dnf cache
  ansible.builtin.dnf:
    update_cache: true

- name: Install vector
  ansible.builtin.dnf:
    name: "/tmp/vector-{{ vector_version }}.rpm"
    state: present
    disable_gpg_check: true
  changed_when: false
  tags:
    - vector
    - install
  become: true

- name: Deploy vector configuration
  ansible.builtin.template:
    src: templates/vector.yaml.j2
    dest: "{{ vector_config_path }}"
    mode: '0644'
  notify: Start vector service
  tags:
    - vector
    - config
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - vector
    - restart
