---
- name: Print pkgs manager
  ansible.builtin.debug:
    msg: "PKGs: {{ pkgs }}"

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"

- name: update yum cache
  ansible.builtin.yum:
    update_cache: yes
  when: ansible_pkg_mgr == "yum"

- name: update apk cache
  community.general.apk:
    update_cache: yes
  when: ansible_pkg_mgr == "apk"

# - name: update dnf cache
#   ansible.builtin.dnf:
#     update_cache: yes
#   when: ansible_pkg_mgr == "dnf"

- name: update zypper cache
  community.general.zypper:
    name: zypper
    update_cache: yes
  when: ansible_pkg_mgr == "zypper"

- name: update pacman cache
  community.general.pacman:
    update_cache: yes
  when: ansible_pkg_mgr == "pacman"  

- name: Install necessary packages (e.g., git, curl)
  ansible.builtin.package:
    name:
      - systemctl
      - curl
    state: present
  become: true # Use become if root privileges are needed for package installation
  when: ansible_service_mgr == "sysvinit"  

# - name: Install necessary packages | Ensure systemd is present
#   ansible.builtin.package:
#     name:
#       - systemd
#     state: present
#   become: true # Use become if root privileges are needed for package installation
#   when: ansible_service_mgr == "systemd"  