---

- name: VECTOR | Ensure vector group
  group:
    name: "{{ vector_group }}"
    system: yes
    state: present

- name: VECTOR | Ensure vector user
  user:
    name: "{{ vector_user }}"
    group: "{{ vector_group }}"
    groups: "{{ vector_groups | default('') }}"
    system: yes
    shell: /usr/sbin/nologin
    createhome: no
    append: True

- name: VECTOR | Ensure skeleton paths
  file:
    dest: "{{ item }}"
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ vector_skeleton_paths }}"
