#SPDX-License-Identifier: MIT-0
---
- name: Start vector service
  ansible.builtin.service:
    name: vector
    state: started
  tags:
    - vector
    - restartservice
  become: true
  
- name: Restart vector
  ansible.builtin.systemd_service:
    name: vector
    state: restarted
  when: vector_service_state != 'stopped'

- name: Reload vector
  ansible.builtin.systemd_service:
    name: vector
    state: reloaded
  when: vector_service_state != 'stopped'

- name: restart vector
  ansible.builtin.service:
    state: restarted
    #daemon_reload: yes
    name: vector
