---

# Dependency management (download roles/collections)
dependency:
  name: galaxy
  options:
    ignore-certs: false
    ignore-errors: false

prerun: false

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: ubuntu24
    image: ubuntu:latest
    #command: /lib/systemd/systemd
    dockerfile: ../Dockerfile.j2
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup

  - name: rocky9
    image: rockylinux:9
    dockerfile: ../Dockerfile.j2
    #command: /lib/systemd/systemd
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../"

verifier:
  name: ansible
